name: voyager
description: The widget router and basic dependency injection library for Flutter. Define navigation paths in YAML and power them up with custom plugins.
version: 1.1.4
author: Lukasz Wisniewski <luke.cherrish@gmail.com>
homepage: https://github.com/vishna/voyager

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^2.1.16
  sprintf: ^4.0.2
  provider: '>=3.0.0 <3.5.0'

dev_dependencies:
  glob: ^1.1.7
  flutter_test:
    sdk: flutter

flutter:
