name: voyager
description: The widget router and basic dependency injection library for Flutter. Define navigation paths in YAML and power them up with custom plugins.
version: 3.0.0
homepage: https://github.com/vishna/voyager

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  provider: ^5.0.0-nullsafety.1
  sprintf: ^6.0.0-nullsafety
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  glob: ^2.0.0
